# Generated by Django 3.2.7 on 2022-10-25 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryoCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetID', models.CharField(max_length=50, verbose_name='Asset ID')),
                ('asset_status', models.CharField(max_length=50, verbose_name='Asset Qualification Status')),
                ('functional_area', models.CharField(max_length=50, verbose_name='functional_area')),
                ('pm_contact', models.CharField(max_length=50, verbose_name='PM Contact')),
                ('product', models.CharField(max_length=50, verbose_name='product')),
                ('execution_priority', models.CharField(max_length=50, null=True, verbose_name='Execution Priority')),
                ('charge_control', models.CharField(max_length=50, null=True, verbose_name='Change Control')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Manufacturer')),
                ('serial_number', models.IntegerField(verbose_name='S/N')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('firmware_software_version', models.CharField(max_length=50, null=True, verbose_name='Firmware/Software Version')),
                ('equipment_class', models.CharField(max_length=50, verbose_name='Equipment Class')),
                ('system_owner', models.CharField(max_length=50, verbose_name='System Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Implementation_crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemsmonitoring', models.CharField(max_length=50, verbose_name='BEMS Monitoring')),
                ('bmramInrollment', models.CharField(max_length=50, verbose_name='BMRAM Inrollment')),
                ('brmram_PM_Cal', models.CharField(max_length=50, verbose_name='BMRAM PM/Cal')),
                ('regul_determination_status', models.CharField(max_length=50, verbose_name='Regulatory Determination Status')),
                ('regul_determination_form_no', models.CharField(max_length=50, verbose_name='Regulatory Determination(Form-001404) Number')),
                ('installation_status', models.CharField(max_length=50, verbose_name='Installation Status')),
                ('config_specific_status', models.CharField(max_length=50, null=True, verbose_name='Configuration Specification Status')),
                ('config_specific_number', models.CharField(max_length=50, verbose_name='Configuration Specification Number')),
                ('urs_number', models.CharField(max_length=50, verbose_name='URS Number')),
                ('urs_status', models.CharField(max_length=50, verbose_name='URS Status')),
                ('operational_sop', models.CharField(max_length=50, verbose_name='operational_sop')),
                ('operational_sop_number', models.CharField(max_length=50, verbose_name='Operational SOP Number')),
                ('maintaienance_sop_status', models.CharField(max_length=50, verbose_name='Maintenance SOP Status')),
                ('maintaienance_sop_number', models.CharField(max_length=50, verbose_name='Maintenance SOP Number')),
                ('admin_sop_status', models.CharField(max_length=50, verbose_name='Admin SOP Status')),
                ('admin_sop_number', models.CharField(max_length=50, null=True, verbose_name='Admin SOP Number')),
                ('logbook', models.CharField(max_length=50, verbose_name='Logbook')),
                ('it_form_0024_status', models.CharField(max_length=50, verbose_name='IT-FRM-0024 Status')),
                ('it_form_0024_number', models.CharField(max_length=50, verbose_name='IT-FRM-0024 Number')),
                ('cryocart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.cryocart')),
            ],
        ),
    ]
