# Generated by Django 3.2.7 on 2022-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation_crypto',
            name='admin_sop_status',
            field=models.CharField(max_length=50, null=True, verbose_name='Admin SOP Status'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='config_specific_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Configuration Specification Number'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='it_form_0024_number',
            field=models.CharField(max_length=50, null=True, verbose_name='IT-FRM-0024 Number'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='it_form_0024_status',
            field=models.CharField(max_length=50, null=True, verbose_name='IT-FRM-0024 Status'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='logbook',
            field=models.CharField(max_length=50, null=True, verbose_name='Logbook'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='maintaienance_sop_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Maintenance SOP Number'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='maintaienance_sop_status',
            field=models.CharField(max_length=50, null=True, verbose_name='Maintenance SOP Status'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='operational_sop',
            field=models.CharField(max_length=50, null=True, verbose_name='operational_sop'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='operational_sop_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Operational SOP Number'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='urs_number',
            field=models.CharField(max_length=50, null=True, verbose_name='URS Number'),
        ),
        migrations.AlterField(
            model_name='implementation_crypto',
            name='urs_status',
            field=models.CharField(max_length=50, null=True, verbose_name='URS Status'),
        ),
    ]
