# Generated by Django 3.2.7 on 2022-11-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20221027_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation_crypto',
            name='cryocart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation', to='assets.cryocart'),
        ),
        migrations.CreateModel(
            name='VENDOR_IOQ_PROTOCOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, null=True, verbose_name='Document Number')),
                ('approval_date', models.DateField(null=True, verbose_name='Approval Date')),
                ('cryocart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vender_protocol', to='assets.cryocart')),
            ],
        ),
    ]
